#!/usr/bin/env python3
"""Export an LBP+LogReg model (JSON) to a C header for firmware integration.

Usage
  python tools/export_lbp_lr_header.py --model models/lbp_lr_model.json --out firmware/atoms3r_m12_streamer/include/model_lbp_lr.h

Tip (uv)
  cd collector
  uv run python ../tools/export_lbp_lr_header.py --model ../models/lbp_lr_model.json --out ../firmware/atoms3r_m12_streamer/include/model_lbp_lr.h
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict


def load_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def write_header(out_path: Path, model: Dict[str, Any], header_guard: str) -> None:
    w = model.get("model", {}).get("weights", [])
    b = float(model.get("model", {}).get("bias", 0.0))
    feat = model.get("feature", {})
    bins = int(feat.get("lbp", {}).get("bins", len(w) if w else 256))
    thr = float(model.get("train", {}).get("threshold", {}).get("threshold", 0.5))

    if len(w) != bins:
        raise ValueError(f"weights length ({len(w)}) != bins ({bins})")

    # Keep formatting stable for diffs.
    lines = []
    lines.append(f"#ifndef {header_guard}\n")
    lines.append(f"#define {header_guard}\n\n")
    lines.append("// Auto-generated by tools/export_lbp_lr_header.py\n")
    lines.append("// Model type: LBP histogram (256 bins) + Logistic Regression\n\n")
    lines.append(f"#define LBP_LR_BINS {bins}\n")
    lines.append(f"static const float LBP_LR_BIAS = {b:.8f}f;\n")
    lines.append(f"static const float LBP_LR_THRESHOLD = {thr:.6f}f;\n\n")

    # Weights array
    lines.append("static const float LBP_LR_WEIGHTS[LBP_LR_BINS] = {\n")
    for i in range(bins):
        if i % 8 == 0:
            lines.append("  ")
        lines.append(f"{float(w[i]):.8f}f")
        if i != bins - 1:
            lines.append(", ")
        if i % 8 == 7 or i == bins - 1:
            lines.append("\n")
    lines.append("};\n\n")

    lines.append("#endif\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(lines), encoding="utf-8")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", type=str, required=True)
    ap.add_argument("--out", type=str, required=True)
    ap.add_argument("--guard", type=str, default="MODEL_LBP_LR_H")
    args = ap.parse_args()

    model_path = Path(args.model)
    out_path = Path(args.out)

    model = load_json(model_path)
    if model.get("type") != "lbp_lr":
        raise SystemExit(f"Unsupported model type: {model.get('type')}")

    write_header(out_path, model, header_guard=str(args.guard).strip() or "MODEL_LBP_LR_H")
    print("wrote", out_path)


if __name__ == "__main__":
    main()
