/*
  AtomS3R-CAM (GC0308) real-time goosebumps inference

  Pipeline (edge-friendly):
    1) Capture RGB565 (QVGA)
    2) Crop fixed center ROI (ROI_SIZE_PX x ROI_SIZE_PX)
    3) Downsample to INPUT_SIZE x INPUT_SIZE grayscale
    4) Compute 8-neighbor LBP histogram (256 bins)
    5) Logistic Regression: p = sigmoid(dot(w, hist_norm) + b)
    6) EMA smoothing + hysteresis -> binary state

  Model parameters:
    - include/model_lbp_lr.h (auto-generated by tools/export_lbp_lr_header.py)

  Optional:
    - Upload frames to Collector PC (/upload)
    - Post state-change events to Collector (/event)
    - UDP commands: LED control, start/stop upload, calibration
*/

#include <Arduino.h>
#include <WiFi.h>
#include <WiFiUdp.h>
#include <ArduinoJson.h>

#include "esp_camera.h"
#include "img_converters.h"  // fmt2jpg

#include "user_config.h"
#include "board_atoms3r_cam_pins.h"
#include "model_lbp_lr.h"

// -------------------- Runtime state --------------------
static WiFiUDP Udp;
static uint32_t g_frame_id = 0;

// Frame upload (streaming) control
static bool g_upload_enabled = ENABLE_FRAME_UPLOAD;
static uint16_t g_target_fps = TARGET_FPS_DEFAULT;
static uint8_t g_jpeg_quality = JPEG_QUALITY_DEFAULT;
static int g_frame_size = FRAME_SIZE_DEFAULT;

// External LED PWM
static uint8_t g_led_pwm = LED_PWM_DEFAULT;
static const int LEDC_CH = 0;

// Inference state
static float g_prob_raw = NAN;
static float g_prob_ema = NAN;
static bool g_state_on = false;
static float g_thr_on = LBP_LR_THRESHOLD;
static float g_thr_off = (LBP_LR_THRESHOLD - HYSTERESIS_DELTA > 0.0f) ? (LBP_LR_THRESHOLD - HYSTERESIS_DELTA) : 0.0f;
static uint32_t g_last_infer_ms = 0;
static uint32_t g_last_capture_ms = 0;

// Calibration state (baseline p during "no goosebumps" period)
static bool g_calib_active = false;
static uint32_t g_calib_start_ms = 0;
static uint32_t g_calib_n = 0;
static double g_calib_sum = 0.0;
static double g_calib_sum2 = 0.0;

// Buffers (keep static to avoid stack issues)
static uint8_t g_gray[INPUT_SIZE * INPUT_SIZE];
static uint32_t g_hist[LBP_LR_BINS];

// -------------------- Helpers --------------------
static inline float clampf(float x, float lo, float hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

static inline float sigmoidf_clamped(float z) {
  // expf overflows around ~88, but we clamp much tighter for numerical stability.
  z = clampf(z, -15.0f, 15.0f);
  return 1.0f / (1.0f + expf(-z));
}

static inline uint8_t rgb565_to_gray(uint16_t p) {
  // RGB565 -> approximate luma (0..255)
  // Expand to 8-bit first.
  const uint8_t r8 = (uint8_t)(((p >> 11) & 0x1F) << 3);
  const uint8_t g8 = (uint8_t)(((p >> 5) & 0x3F) << 2);
  const uint8_t b8 = (uint8_t)((p & 0x1F) << 3);
  // ITU-R BT.601 luma approx: 0.299R + 0.587G + 0.114B
  // integer: (77R + 150G + 29B) >> 8
  const uint16_t y = (uint16_t)(r8 * 77u + g8 * 150u + b8 * 29u) >> 8;
  return (uint8_t)y;
}

static void camera_power_enable() {
  // AtomS3R-CAM uses POWER_N (GPIO18) active-low enable.
  // We intentionally "power-cycle" the camera enable pin to avoid rare
  // probe failures at boot (ESP_ERR_NOT_FOUND).
  pinMode(CAM_PIN_POWER_N, OUTPUT);
  digitalWrite(CAM_PIN_POWER_N, HIGH);  // disable
  delay(CAM_POWER_OFF_DELAY_MS);
  digitalWrite(CAM_PIN_POWER_N, LOW);   // enable
  delay(CAM_POWER_ON_DELAY_MS);
}

static void led_init() {
  ledcSetup(LEDC_CH, LED_PWM_FREQ_HZ, LED_PWM_RES_BITS);
  ledcAttachPin(LED_PWM_PIN, LEDC_CH);
  ledcWrite(LEDC_CH, g_led_pwm);
}

static void led_set(uint8_t pwm) {
  g_led_pwm = pwm;
  ledcWrite(LEDC_CH, g_led_pwm);
}

static bool wifi_connect() {
  WiFi.mode(WIFI_STA);
  WiFi.setSleep(false);
  WiFi.begin(WIFI_SSID, WIFI_PASS);

  Serial.printf("[WiFi] connecting to %s\n", WIFI_SSID);
  const uint32_t t0 = millis();
  while (WiFi.status() != WL_CONNECTED) {
    delay(300);
    Serial.print(".");
    if (millis() - t0 > 20000) {
      Serial.println("\n[WiFi] timeout");
      return false;
    }
  }
  Serial.printf("\n[WiFi] connected. IP=%s RSSI=%d\n", WiFi.localIP().toString().c_str(), WiFi.RSSI());
  return true;
}

static void udp_init() {
  Udp.begin(UDP_CMD_PORT);
  Serial.printf("[UDP] listening on %u\n", UDP_CMD_PORT);
}

static camera_config_t make_camera_config() {
  camera_power_enable();

  camera_config_t config;
  config.ledc_channel = LEDC_CHANNEL_1;
  config.ledc_timer   = LEDC_TIMER_1;

  config.pin_d0       = CAM_PIN_D0;
  config.pin_d1       = CAM_PIN_D1;
  config.pin_d2       = CAM_PIN_D2;
  config.pin_d3       = CAM_PIN_D3;
  config.pin_d4       = CAM_PIN_D4;
  config.pin_d5       = CAM_PIN_D5;
  config.pin_d6       = CAM_PIN_D6;
  config.pin_d7       = CAM_PIN_D7;
  config.pin_xclk     = CAM_PIN_XCLK;
  config.pin_pclk     = CAM_PIN_PCLK;
  config.pin_vsync    = CAM_PIN_VSYNC;
  config.pin_href     = CAM_PIN_HREF;
  config.pin_sccb_sda = CAM_PIN_SIOD;
  config.pin_sccb_scl = CAM_PIN_SIOC;

  // IMPORTANT:
  // - esp_camera treats pin_pwdn as active-high power-down.
  // - AtomS3R-CAM GPIO18 is POWER_N (active-low enable).
  // So we control POWER_N manually and keep pin_pwdn unused.
  config.pin_pwdn     = -1;
  config.pin_reset    = CAM_PIN_RESET;

  // Put camera SCCB on I2C port 1.
  config.sccb_i2c_port = 1;

  // M5Stack docs recommend XCLK 20MHz for AtomS3R-CAM.
  config.xclk_freq_hz = 20000000;

  // GC0308 does not output JPEG natively. Capture RGB565.
  config.pixel_format = PIXFORMAT_RGB565;

  config.frame_size   = (framesize_t)g_frame_size;
  config.jpeg_quality = g_jpeg_quality;
  config.fb_count     = 2;
  config.fb_location  = CAMERA_FB_IN_PSRAM;
  config.grab_mode    = CAMERA_GRAB_LATEST;

  return config;
}

static bool camera_init() {
  if (!psramFound()) {
    Serial.println("[CAM] PSRAM not found. This board should have 8MB PSRAM.");
  } else {
    Serial.printf("[CAM] PSRAM OK. size=%u\n", ESP.getPsramSize());
  }

  camera_config_t config = make_camera_config();
  esp_err_t err = esp_camera_init(&config);
  if (err != ESP_OK) {
    Serial.printf("[CAM] init failed 0x%x\n", (int)err);
    return false;
  }

  sensor_t* s = esp_camera_sensor_get();
  if (s) {
    // You can tweak sensor settings here if needed.
    // s->set_brightness(s, 0);
    // s->set_contrast(s, 0);
  }

  Serial.println("[CAM] init OK");
  return true;
}

static bool camera_init_with_retry() {
  const uint8_t max_tries = (CAM_INIT_MAX_RETRIES < 1) ? 1 : CAM_INIT_MAX_RETRIES;
  for (uint8_t i = 0; i < max_tries; i++) {
    Serial.printf("[CAM] init try %u/%u\n", (unsigned)(i + 1), (unsigned)max_tries);

    if (camera_init()) {
      return true;
    }

    // Best-effort cleanup before retry
    esp_camera_deinit();
    delay(CAM_RETRY_DELAY_MS);
  }
  return false;
}

// Convert RGB565 fb buffer to JPEG (software)
static bool fb_to_jpeg(const camera_fb_t* fb, uint8_t jpeg_quality, uint8_t** out_buf, size_t* out_len) {
  *out_buf = nullptr;
  *out_len = 0;
  if (!fb || !fb->buf || fb->len == 0) return false;

  // Encode RGB565 -> JPEG
  bool ok = fmt2jpg(
    fb->buf, fb->len,
    fb->width, fb->height,
    fb->format,
    jpeg_quality,
    out_buf,
    out_len
  );
  return ok;
}

static bool http_upload_frame_with_pred(const camera_fb_t* fb) {
  WiFiClient client;
  client.setTimeout(4000);

  if (!client.connect(COLLECTOR_HOST, COLLECTOR_PORT)) {
    Serial.println("[HTTP] connect failed");
    return false;
  }

  uint8_t* jpg_buf = nullptr;
  size_t jpg_len = 0;
  bool need_free = false;

  if (!fb_to_jpeg(fb, g_jpeg_quality, &jpg_buf, &jpg_len)) {
    Serial.println("[JPEG] encode failed");
    return false;
  }
  need_free = true;

  String boundary = "----gbBoundary";
  boundary += String((uint32_t)esp_random(), HEX);

  auto part_field = [&](const char* name, const String& value) -> String {
    String p;
    p += "--" + boundary + "\r\n";
    p += "Content-Disposition: form-data; name=\"";
    p += name;
    p += "\"\r\n\r\n";
    p += value;
    p += "\r\n";
    return p;
  };

  String head;
  head.reserve(768);
  head += part_field("frame_id", String(g_frame_id));
  head += part_field("device_ts_ms", String((uint32_t)millis()));
  head += part_field("width", String(fb->width));
  head += part_field("height", String(fb->height));
  head += part_field("led_pwm", String(g_led_pwm));

  // Add inference fields (Collector currently ignores unknown fields, but
  // this is useful for future server-side logging without changing firmware).
  if (isfinite(g_prob_raw)) head += part_field("gb_prob", String(g_prob_raw, 6));
  if (isfinite(g_prob_ema)) head += part_field("gb_prob_ema", String(g_prob_ema, 6));
  head += part_field("gb_state", String(g_state_on ? 1 : 0));
  head += part_field("gb_thr_on", String(g_thr_on, 6));
  head += part_field("gb_thr_off", String(g_thr_off, 6));

  head += "--" + boundary + "\r\n";
  head += "Content-Disposition: form-data; name=\"image\"; filename=\"frame.jpg\"\r\n";
  head += "Content-Type: image/jpeg\r\n\r\n";

  String tail;
  tail.reserve(64);
  tail += "\r\n--" + boundary + "--\r\n";

  const uint32_t content_length = head.length() + jpg_len + tail.length();

  client.print(String("POST ") + COLLECTOR_UPLOAD_PATH + " HTTP/1.1\r\n");
  client.print(String("Host: ") + COLLECTOR_HOST + "\r\n");
  client.print("User-Agent: atoms3r-cam-infer\r\n");
  client.print(String("Content-Type: multipart/form-data; boundary=") + boundary + "\r\n");
  client.print(String("Content-Length: ") + content_length + "\r\n");
  client.print("Connection: close\r\n\r\n");

  client.print(head);
  client.write(jpg_buf, jpg_len);
  client.print(tail);

  // Best-effort response read
  uint32_t t0 = millis();
  while (client.connected() && millis() - t0 < 1000) {
    while (client.available()) {
      (void)client.read();
    }
    break;
  }
  client.stop();

  if (need_free && jpg_buf) free(jpg_buf);
  return true;
}

static bool http_post_event(const char* type, int value, const char* note) {
  WiFiClient client;
  client.setTimeout(3000);

  if (!client.connect(COLLECTOR_HOST, COLLECTOR_PORT)) {
    Serial.println("[HTTP] event connect failed");
    return false;
  }

  StaticJsonDocument<256> doc;
  doc["type"] = type;
  doc["value"] = value;
  doc["note"] = note ? note : "";

  char body[256];
  size_t body_len = serializeJson(doc, body, sizeof(body));

  client.print(String("POST ") + COLLECTOR_EVENT_PATH + " HTTP/1.1\r\n");
  client.print(String("Host: ") + COLLECTOR_HOST + "\r\n");
  client.print("User-Agent: atoms3r-cam-infer\r\n");
  client.print("Content-Type: application/json\r\n");
  client.print(String("Content-Length: ") + String((uint32_t)body_len) + "\r\n");
  client.print("Connection: close\r\n\r\n");
  client.write((const uint8_t*)body, body_len);

  // Best-effort response read
  uint32_t t0 = millis();
  while (client.connected() && millis() - t0 < 800) {
    while (client.available()) {
      (void)client.read();
    }
    break;
  }
  client.stop();
  return true;
}

static bool extract_center_roi_downsample_gray(const camera_fb_t* fb, uint8_t* out_gray) {
  if (!fb || !fb->buf) return false;
  if (fb->format != PIXFORMAT_RGB565) {
    Serial.printf("[INF] unsupported fb format=%d (need RGB565)\n", (int)fb->format);
    return false;
  }

  const int W = (int)fb->width;
  const int H = (int)fb->height;
  const int roi = ROI_SIZE_PX;
  const int S = INPUT_SIZE;

  if (roi <= 0 || S <= 0) return false;
  if (roi > W || roi > H) return false;

  const int x0 = (W - roi) / 2;
  const int y0 = (H - roi) / 2;

  const uint16_t* pix = (const uint16_t*)fb->buf;

  // Nearest-neighbor downsample
  for (int oy = 0; oy < S; oy++) {
    const int sy = y0 + (oy * roi) / S;
    const uint16_t* row = pix + sy * W;
    for (int ox = 0; ox < S; ox++) {
      const int sx = x0 + (ox * roi) / S;
      out_gray[oy * S + ox] = rgb565_to_gray(row[sx]);
    }
  }
  return true;
}

static void lbp_hist_8(const uint8_t* gray, int S, uint32_t* hist) {
  memset(hist, 0, sizeof(uint32_t) * LBP_LR_BINS);

  // 8-neighbor LBP, clockwise bits: 7..0
  for (int y = 1; y < S - 1; y++) {
    const int ym1 = (y - 1) * S;
    const int y0  = y * S;
    const int yp1 = (y + 1) * S;
    for (int x = 1; x < S - 1; x++) {
      const uint8_t c = gray[y0 + x];
      uint8_t code = 0;
      code |= (gray[ym1 + (x - 1)] >= c) ? (1u << 7) : 0;
      code |= (gray[ym1 + (x    )] >= c) ? (1u << 6) : 0;
      code |= (gray[ym1 + (x + 1)] >= c) ? (1u << 5) : 0;
      code |= (gray[y0  + (x + 1)] >= c) ? (1u << 4) : 0;
      code |= (gray[yp1 + (x + 1)] >= c) ? (1u << 3) : 0;
      code |= (gray[yp1 + (x    )] >= c) ? (1u << 2) : 0;
      code |= (gray[yp1 + (x - 1)] >= c) ? (1u << 1) : 0;
      code |= (gray[y0  + (x - 1)] >= c) ? (1u << 0) : 0;
      hist[code]++;
    }
  }
}

static float lbp_lr_predict_prob(const uint32_t* hist, int total_pixels) {
  // dot(w, hist_norm) + b
  // hist_norm[i] = hist[i] / total_pixels
  float acc = LBP_LR_BIAS;
  float sum = 0.0f;
  for (int i = 0; i < LBP_LR_BINS; i++) {
    sum += LBP_LR_WEIGHTS[i] * (float)hist[i];
  }
  acc += sum / (float)total_pixels;
  return sigmoidf_clamped(acc);
}

static void update_prob_ema(float p, float dt_sec) {
  if (!isfinite(g_prob_ema)) {
    g_prob_ema = p;
    return;
  }
  const float tau = (PROB_EMA_TAU_SEC > 1e-3f) ? PROB_EMA_TAU_SEC : 0.8f;
  const float a = expf(-dt_sec / tau);
  g_prob_ema = a * g_prob_ema + (1.0f - a) * p;
}

static void calib_start() {
  g_calib_active = true;
  g_calib_start_ms = millis();
  g_calib_n = 0;
  g_calib_sum = 0.0;
  g_calib_sum2 = 0.0;
  Serial.println("[CALIB] start");
}

static void calib_done_and_update_threshold() {
  g_calib_active = false;
  const uint32_t dur = millis() - g_calib_start_ms;
  if (dur < CALIB_MIN_MS || g_calib_n < 10) {
    Serial.printf("[CALIB] too short (dur=%ums n=%u). ignored\n", (unsigned)dur, (unsigned)g_calib_n);
    return;
  }

  const double mean = g_calib_sum / (double)g_calib_n;
  const double var = (g_calib_sum2 / (double)g_calib_n) - mean * mean;
  const double std = sqrt(var > 1e-9 ? var : 1e-9);

  float thr_on = (float)(mean + (double)CALIB_K_ON * std);
  float thr_off = (float)(mean + (double)CALIB_K_OFF * std);

  thr_on = clampf(thr_on, 0.01f, 0.99f);
  thr_off = clampf(thr_off, 0.0f, thr_on);

  g_thr_on = thr_on;
  g_thr_off = thr_off;

  Serial.printf("[CALIB] done: mean=%.4f std=%.4f thr_on=%.4f thr_off=%.4f\n", (float)mean, (float)std, g_thr_on, g_thr_off);

  if (ENABLE_EVENT_POST) {
    char note[96];
    snprintf(note, sizeof(note), "mean=%.3f std=%.3f thr_on=%.3f thr_off=%.3f", (float)mean, (float)std, g_thr_on, g_thr_off);
    (void)http_post_event("gb_calib_done", 1, note);
  }
}

static void send_udp_response(const IPAddress& ip, uint16_t port, const JsonDocument& doc) {
  char out[384];
  size_t n = serializeJson(doc, out, sizeof(out));
  Udp.beginPacket(ip, port);
  Udp.write((const uint8_t*)out, n);
  Udp.endPacket();
}

static void handle_udp_cmd() {
  int packetSize = Udp.parsePacket();
  if (packetSize <= 0) return;

  char buf[512];
  int len = Udp.read(buf, sizeof(buf) - 1);
  if (len <= 0) return;
  buf[len] = '\0';

  StaticJsonDocument<256> in;
  DeserializationError err = deserializeJson(in, buf);
  StaticJsonDocument<384> out;

  IPAddress rip = Udp.remoteIP();
  uint16_t rport = Udp.remotePort();

  if (err) {
    out["ok"] = false;
    out["error"] = "json_parse_failed";
    send_udp_response(rip, rport, out);
    return;
  }

  const char* cmd = in["cmd"] | "";
  out["cmd"] = cmd;

  if (strcmp(cmd, "ping") == 0) {
    out["ok"] = true;
    out["device_ts_ms"] = (uint32_t)millis();
    out["ip"] = WiFi.localIP().toString();
    out["upload"] = g_upload_enabled;
    out["led_pwm"] = g_led_pwm;
    out["gb_state"] = g_state_on ? 1 : 0;
    if (isfinite(g_prob_raw)) out["gb_prob"] = g_prob_raw;
    if (isfinite(g_prob_ema)) out["gb_prob_ema"] = g_prob_ema;
    out["thr_on"] = g_thr_on;
    out["thr_off"] = g_thr_off;
    out["calib_active"] = g_calib_active;
  } else if (strcmp(cmd, "start_upload") == 0) {
    g_upload_enabled = true;
    out["ok"] = true;
    out["upload"] = true;
  } else if (strcmp(cmd, "stop_upload") == 0) {
    g_upload_enabled = false;
    out["ok"] = true;
    out["upload"] = false;
  } else if (strcmp(cmd, "set_led") == 0) {
    int pwm = in["pwm"] | -1;
    if (pwm < 0) pwm = 0;
    if (pwm > 255) pwm = 255;
    led_set((uint8_t)pwm);
    out["ok"] = true;
    out["pwm"] = pwm;
  } else if (strcmp(cmd, "set_param") == 0) {
    if (in.containsKey("target_fps")) {
      int fps = in["target_fps"] | (int)g_target_fps;
      if (fps < 1) fps = 1;
      if (fps > 30) fps = 30;
      g_target_fps = (uint16_t)fps;
      out["target_fps"] = fps;
    }
    if (in.containsKey("jpeg_quality")) {
      int q = in["jpeg_quality"] | (int)g_jpeg_quality;
      if (q < 2) q = 2;
      if (q > 63) q = 63;
      g_jpeg_quality = (uint8_t)q;
      out["jpeg_quality"] = q;
    }
    if (in.containsKey("thr_on")) {
      g_thr_on = (float)(in["thr_on"] | (double)g_thr_on);
      g_thr_on = clampf(g_thr_on, 0.01f, 0.99f);
      out["thr_on"] = g_thr_on;
    }
    if (in.containsKey("thr_off")) {
      g_thr_off = (float)(in["thr_off"] | (double)g_thr_off);
      g_thr_off = clampf(g_thr_off, 0.0f, g_thr_on);
      out["thr_off"] = g_thr_off;
    }
    out["ok"] = true;
  } else if (strcmp(cmd, "calib_start") == 0) {
    calib_start();
    out["ok"] = true;
  } else if (strcmp(cmd, "calib_done") == 0) {
    calib_done_and_update_threshold();
    out["ok"] = true;
  } else if (strcmp(cmd, "reboot") == 0) {
    out["ok"] = true;
    send_udp_response(rip, rport, out);
    delay(100);
    ESP.restart();
    return;
  } else {
    out["ok"] = false;
    out["error"] = "unknown_cmd";
  }

  send_udp_response(rip, rport, out);
}

static void infer_loop_once() {
  const uint32_t now_ms = millis();
  const uint32_t frame_interval_ms = (g_target_fps > 0) ? (1000UL / g_target_fps) : 100;

  // Pace capture to target FPS
  if (g_last_capture_ms != 0 && (now_ms - g_last_capture_ms) < frame_interval_ms) {
    return;
  }
  g_last_capture_ms = now_ms;

  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) {
    Serial.println("[CAM] capture failed");
    delay(10);
    return;
  }

  // --- Inference ---
  if (extract_center_roi_downsample_gray(fb, g_gray)) {
    lbp_hist_8(g_gray, INPUT_SIZE, g_hist);
    const int total = (INPUT_SIZE - 2) * (INPUT_SIZE - 2);
    g_prob_raw = lbp_lr_predict_prob(g_hist, total);

    float dt_sec = 0.0f;
    if (g_last_infer_ms != 0) dt_sec = (float)(now_ms - g_last_infer_ms) / 1000.0f;
    g_last_infer_ms = now_ms;
    if (dt_sec <= 0.0f) dt_sec = (float)frame_interval_ms / 1000.0f;

    update_prob_ema(g_prob_raw, dt_sec);

    // Calibration accumulation uses EMA (more stable)
    if (g_calib_active && isfinite(g_prob_ema)) {
      g_calib_n++;
      g_calib_sum += (double)g_prob_ema;
      g_calib_sum2 += (double)g_prob_ema * (double)g_prob_ema;
    }

    // Hysteresis state machine
    bool prev_state = g_state_on;
    if (!g_state_on) {
      if (isfinite(g_prob_ema) && g_prob_ema >= g_thr_on) {
        g_state_on = true;
      }
    } else {
      if (isfinite(g_prob_ema) && g_prob_ema <= g_thr_off) {
        g_state_on = false;
      }
    }

    if (prev_state != g_state_on) {
      Serial.printf("[GB] state change: %d -> %d (p=%.3f ema=%.3f thr_on=%.3f thr_off=%.3f)\n",
                    prev_state ? 1 : 0, g_state_on ? 1 : 0,
                    isfinite(g_prob_raw) ? g_prob_raw : -1.0f,
                    isfinite(g_prob_ema) ? g_prob_ema : -1.0f,
                    g_thr_on, g_thr_off);

      if (ENABLE_EVENT_POST) {
        char note[80];
        snprintf(note, sizeof(note), "p=%.3f ema=%.3f", (float)g_prob_raw, (float)g_prob_ema);
        (void)http_post_event(g_state_on ? "gb_pred_on" : "gb_pred_off", 1, note);
      }
    }

    // Periodic print
    if (PRINT_EVERY_N_FRAMES > 0 && (g_frame_id % PRINT_EVERY_N_FRAMES) == 0) {
      Serial.printf("[INF] frame=%lu p=%.3f ema=%.3f state=%d thr_on=%.3f thr_off=%.3f upload=%d\n",
                    (unsigned long)g_frame_id,
                    isfinite(g_prob_raw) ? g_prob_raw : -1.0f,
                    isfinite(g_prob_ema) ? g_prob_ema : -1.0f,
                    g_state_on ? 1 : 0,
                    g_thr_on,
                    g_thr_off,
                    g_upload_enabled ? 1 : 0);
    }
  }

  // --- Optional upload ---
  if (g_upload_enabled) {
    (void)http_upload_frame_with_pred(fb);
  }

  esp_camera_fb_return(fb);
  g_frame_id++;
}

// -------------------- Arduino entry --------------------
void setup() {
  Serial.begin(115200);
  delay(1000);

  Serial.println("\n== AtomS3R-CAM LBP+LR Realtime Inference ==");

  // To reduce boot-time failures on some boards, we can initialize the camera
  // BEFORE turning on WiFi and before ramping up illumination PWM.
  // (WiFi connection can cause a brief inrush that perturbs the sensor power/I2C)
  g_led_pwm = 0;
  led_init();
  Serial.println("[SYS] LED PWM init OK (startup at 0)");

  if (CAM_INIT_BEFORE_WIFI) {
    const bool cam_ok = camera_init_with_retry();
    if (!cam_ok) {
      Serial.println("[CAM] init failed after retries.");
      if (CAM_RESTART_ON_INIT_FAIL) {
        Serial.println("[CAM] restarting...");
        delay(300);
        ESP.restart();
      }
      Serial.println("[CAM] HALT.");
      while (true) delay(1000);
    }
    // After camera init, restore illumination PWM
    led_set(LED_PWM_DEFAULT);
  }

  while (!wifi_connect()) {
    delay(2000);
  }

  udp_init();

  if (!CAM_INIT_BEFORE_WIFI) {
    const bool cam_ok = camera_init_with_retry();
    if (!cam_ok) {
      Serial.println("[CAM] init failed after retries.");
      if (CAM_RESTART_ON_INIT_FAIL) {
        Serial.println("[CAM] restarting...");
        delay(300);
        ESP.restart();
      }
      Serial.println("[CAM] HALT.");
      while (true) delay(1000);
    }
    led_set(LED_PWM_DEFAULT);
  }

  // Init thresholds
  g_thr_on = clampf(LBP_LR_THRESHOLD, 0.01f, 0.99f);
  g_thr_off = clampf(g_thr_on - HYSTERESIS_DELTA, 0.0f, g_thr_on);

  Serial.printf("[SYS] model_thr=%.3f (thr_on=%.3f thr_off=%.3f)\n", (float)LBP_LR_THRESHOLD, g_thr_on, g_thr_off);
  Serial.printf("[SYS] ROI=%dx%d -> %dx%d, fps=%u, upload=%d\n", ROI_SIZE_PX, ROI_SIZE_PX, INPUT_SIZE, INPUT_SIZE, (unsigned)g_target_fps, g_upload_enabled ? 1 : 0);

  if (ENABLE_EVENT_POST) {
    (void)http_post_event("gb_device_boot", 1, "atoms3r_cam_infer");
  }
}

void loop() {
  handle_udp_cmd();

  infer_loop_once();

  if (WiFi.status() != WL_CONNECTED) {
    Serial.println("[WiFi] disconnected, reconnecting...");
    g_upload_enabled = false;
    WiFi.disconnect(true);
    delay(300);
    while (!wifi_connect()) {
      delay(1500);
    }
    g_upload_enabled = ENABLE_FRAME_UPLOAD;
  }
}
